[View in Colaboratory](https://colab.research.google.com/github/eventia/deepLearningOpenLecture/blob/master/Learn_argmax.ipynb)

In [2]:
import numpy as np

a = np.arange(10).reshape(2,5)
a[0,2]=100
a[0,4]=50
a[1,2]=25
print(a)

[[  0   1 100   3  50]
 [  5   6  25   8   9]]


In [3]:
np.argmax(a, axis=None)

2

In [4]:
np.argmax(a, axis=0)

array([1, 1, 0, 1, 0])

In [5]:
np.argmax(a, axis=1)

array([2, 2])