[View in Colaboratory](https://colab.research.google.com/github/eventia/deepLearningOpenLecture/blob/master/TrialFunction.ipynb)

In [2]:
import numpy as np

np.random.randn(3, 4, 2, 2) # 3행 10열짜리 행렬에 정규분포(가우시안분포)에 해당되는 난수를 넣는다.
# input_size, hidden_size = 28*28, 100
# np.random.randn(input_size, hidden_size)


array([[[[ 0.6771567 , -1.18279209],
         [ 0.64139007, -0.70090292]],

        [[-0.42356374,  0.14244006],
         [-1.27545139, -0.3196059 ]],

        [[-0.36473266, -0.47678813],
         [-0.18698527,  1.33351338]],

        [[ 0.49582258,  0.88989586],
         [ 0.48956731, -0.83256167]]],


       [[[-0.13468601,  0.90498092],
         [ 0.95864228, -0.38714454]],

        [[ 0.04819509, -0.29053599],
         [-0.28357349, -0.63070116]],

        [[-0.39383586, -0.31127626],
         [ 0.25591269,  0.84650362]],

        [[-0.51497304, -0.22378073],
         [ 0.85529766, -0.1944232 ]]],


       [[[ 0.03721822, -0.15648575],
         [-0.25739182, -0.81816424]],

        [[ 0.50669306,  1.13104051],
         [ 0.16452321, -1.60274364]],

        [[-0.64640803, -0.8402888 ],
         [ 1.25312374,  2.1273347 ]],

        [[ 0.82765312, -0.21248031],
         [ 0.7542178 , -0.68301681]]]])

In [48]:
numsize = 10000
sum0, sum1, sum2, sum3, sum4 = 0,0,0,0,0
arrA = np.random.randint(5,size=numsize)
for num in range(numsize) :
  if arrA[num]==0 :
    sum0 += 1;
  elif arrA[num]==1 :
    sum1 += 1
  elif arrA[num]==2:
    sum2 += 1
  elif arrA[num]==3:
    sum3 += 1  
  elif arrA[num]==4:
    sum4 += 1
    
print(sum0, sum1, sum2, sum3)

sum = [0,0,0,0,0]
sum = np.zeros(5)
for num in range(numsize) :
  sum[arrA[num]]+=1
print(sum)

1900 1968 1977 2081
[1900. 1968. 1977. 2081. 2074.]


In [65]:
numsize = 10000
arrA = np.random.rand(numsize)

sum = np.zeros(9)
for num in range(numsize):
  for nn in range(10):
    if arrA[num]< nn*0.1:
      sum[nn-1]+=1
      break

print(sum)      


[1000. 1003. 1010. 1027.  978.  983.  997. 1020.  962.]


In [18]:
numsize = 1000
arr_nd = np.random.randn(numsize)+100
arr_rd = np.random.rand(numsize)+100
step = [95,96,97,98,99,100,101,102,103,104]
sum_nd = np.zeros(9)
sum_rd = np.zeros(9)

for num in range(numsize):
  for nn in range(1,10):
    if arr_nd[num]< step[nn]:
      sum_nd[nn-1]+=1
      break

for num in range(numsize):
  for nn in range(1,10):
    if arr_rd[num]< step[nn]:
      sum_rd[nn-1]+=1
      break
      
print(sum_nd)
print(sum_rd) 


# print(arr_rd)

[  0.   3.  12. 128. 317. 370. 148.  21.   1.]
[   0.    0.    0.    0.    0. 1000.    0.    0.    0.]


In [45]:
numsize = 1000
num_mean = 1000
num_std = 100

arr_rd = np.random.rand(numsize)*num_std+num_mean
# step = range(num_mean-5*num_std,num_mean+5*num_std,num_std)
step = range(num_mean,num_mean+num_std+1,int(num_std/10))

sum_rd = np.zeros(10)

for num in range(numsize):
  for nn in range(0,10):
    if arr_rd[num]< step[nn+1]:
      sum_rd[nn]+=1
      break
      
# for num in range(numsize):
#   for nn in range(1,10):
#     if arr_rd[num]< step[nn]:
#       sum_rd[nn-1]+=1
#       break

print("step=",step)
print(sum_rd) 
print(arr_rd)

[102.  90.  88. 106. 105. 104. 101. 100. 114.  90.] 1000.0
step= [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1039.89082464 1023.65042518 1064.67245002 1020.48512372 1094.8966885
 1055.29365545 1041.13192521 1073.59553546 1016.83840395 1015.47441748
 1028.36321025 1085.11690323 1021.49304293 1027.06609886 1047.93186147
 1085.77093976 1033.94489056 1093.7208947  1028.20856967 1076.93061259
 1086.94248916 1007.1033554  1079.20619076 1001.32747991 1042.96803207
 1091.53508214 1017.50079388 1048.60666164 1089.74017776 1048.54490365
 1012.30742841 1052.0807538  1080.97926007 1094.58633234 1028.89017508
 1000.25118548 1072.31206983 1024.64219736 1084.06113521 1036.36005059
 1024.46281439 1091.34594612 1036.84902327 1044.29307825 1084.70939445
 1076.71533479 1008.63898937 1030.5548964  1003.20576972 1061.13611432
 1070.40834797 1033.0517725  1052.9359875  1014.88265262 1078.51538744
 1018.984635   1085.55602858 1061.7395045  1090.68407887 1089.19847805
 103

range(1, 10)
