In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])

In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [38]:
A = np.array(
    [
    [1,2,3],
    [2,4,6],
    [3,6,9]
    ]
)
B = np.array([10,20,30])

In [39]:
np.dot(A,B)

array([140, 280, 420])

In [34]:
X = np.array([0,0,1])

In [35]:
W1 = np.array([[2,2,-1],[2,2,0],[0,-1,-1]])
W2 = np.array([[2,2,-1],[-1,0,0],[2,-1,2]])
W3 = np.array([[2,-1,0],[-1,-1,0],[2,0,0]])

In [36]:
Y = np.dot(W3, np.dot(W2, np.dot(W1,X)))
Y

array([-3,  0, -2])

In [37]:
Y = np.dot(np.dot(np.dot(W3, W2), W1),X)
Y

array([-3,  0, -2])